###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/withInfos

###
GET http://localhost:3000/api/v1/users/4

###
DELETE http://localhost:3000/api/v1/users/3

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "Will Solace",
    "email": "docSunshine@gmail.com",
    "username": "Doctor Sunshine",
    "password": "deathboy",
    "age": 23,
    "admin": false,
    "image": "https://i.pinimg.com/736x/4b/a2/21/4ba221f952bb0cb94e0cfd461a04948a.jpg",
    "address": {
        "street": "1234 Apollo Way",
        "city": "New York",
        "state": "NY",
        "zip": "10001"
    },
    "infos": [
        {
      "title": "Evening Run",
      "date": "2023-10-02",
      "type": "Running",
      "distance": 3.0,
      "duration": 35,
      "calories": 250,
      "avgPace": 10,
      "image": "https://www.verywellfit.com/thmb/1Z6Z9Q1Z9Z9Z9Z9Z9Z9Z9Z9Z9Z9-5c1b1b"
        }
     ]
}

###
PATCH http://localhost:3000/api/v1/users/2
Content-Type: application/json
{
    "name": "Sarah Sue",
}

###
POST http://localhost:3000/api/v1/users/seed

###
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{"email":"joel04mathew@gmail.com","password":"CoolPassword"}

###
POST http://localhost:3000/api/v1/users/logout
###
GET http://localhost:3000/api/v1/users/1/infos

###
POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
    "email": "jane.doe@example.com",
    "password": "SecurePass123"
}

###
GET http://localhost:3000/api/v1/users/joel04mathew@gmail.com/logingInByEmail
